// flow-typed signature: 6e4b562e05795f93d2848963e4429cc3
// flow-typed version: <<STUB>>/@types/node_v^9.4.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
    declare module.exports: any;
}
